### ISSUE TITLE
Milestone 1 Feedback: by Anthony Chiodo and Hayley Boyce

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/college_scorecard#14]
This Feedback was done by: 

- [Anthony Chiodo](https://github.com/apchiodo)
- [Hayley Boyce](https://github.com/hfboyce)

- Lots of information and options. 
- Great used the tabs.
- Loved the information you added underneath the dashboard. 
- [ ] Change the labeling to small, medium and large.
- [ ]  "Number of schools by size" graph when you selected a single size school, this graph creates a square which seems a little odd.
- [ ] Multi-select of many states. 
- [ ] Multi-select radio buttons.
-[ ]  Include state names.
-[ ] Change "frequency" to density.
